import { useState } from 'react'
import Head from 'next/head'

const roleMap = { manufacturer:'Pharmaceutical Manufacturer', distributor:'Distributor / Wholesaler', pharmacy:'Pharmacy / Hospital Chain', regulator:'Regulatory Body / Government', other:'Other Healthcare Org' }
const sizeMap = { small:'Small (<50 staff)', mid:'Mid-size (50–500)', large:'Large (500–5,000)', enterprise:'Enterprise (5,000+)' }
const geoMap  = { africa:'Africa', asia:'Asia / Southeast Asia', europe:'Europe', americas:'Americas', global:'Global / Multi-region' }
const featMap = { verification:'Real-time Product Verification', dashboard:'Chain-of-Custody Dashboard', alerts:'Counterfeit Alert System', analytics:'Supply Chain Analytics', patient:'Patient Mobile App' }
const timeMap = { asap:'As Soon As Possible', '3months':'Within 3 Months', '6months':'Within 6 Months', exploring:'Still Exploring' }

function downloadTXT(s) {
  const lines = [
    '════════════════════════════════════════',
    '   TRUSTICHAIN — CLIENT PROFILE REPORT',
    '════════════════════════════════════════',
    '',
    `  Submitted:     ${new Date(s.submittedAt).toLocaleString('en-GB')}`,
    `  Submission ID: ${s.id}`,
    '',
    '── CONTACT INFORMATION ─────────────────',
    `  Name:          ${s.name}`,
    `  Company:       ${s.company || '—'}`,
    `  Email:         ${s.email}`,
    `  Phone:         ${s.phone || '—'}`,
    '',
    '── ORGANISATION PROFILE ────────────────',
    `  Type:          ${roleMap[s.role] || s.role || '—'}`,
    `  Size:          ${sizeMap[s.size] || s.size || '—'}`,
    `  Region:        ${geoMap[s.region] || s.region || '—'}`,
    '',
    '── REQUIREMENTS ────────────────────────',
    `  Challenges:    ${Array.isArray(s.challenges) ? s.challenges.join(', ') : s.challenges || '—'}`,
    `  Priority:      ${featMap[s.feature] || s.feature || '—'}`,
    `  Timeline:      ${timeMap[s.timeline] || s.timeline || '—'}`,
    '',
    '════════════════════════════════════════',
    '  Generated by TrustiChain Admin Panel',
    `  ${new Date().toLocaleString('en-GB')}`,
    '════════════════════════════════════════',
  ]
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `TrustiChain_${(s.name || 'client').replace(/\s+/g, '_')}_${(s.id || '').slice(-5)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function downloadJSON(s) {
  const enriched = {
    ...s,
    roleLabel: roleMap[s.role] || s.role,
    sizeLabel: sizeMap[s.size] || s.size,
    regionLabel: geoMap[s.region] || s.region,
    featureLabel: featMap[s.feature] || s.feature,
    timelineLabel: timeMap[s.timeline] || s.timeline,
    exportedAt: new Date().toISOString(),
  }
  const blob = new Blob([JSON.stringify(enriched, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `TrustiChain_${(s.name || 'client').replace(/\s+/g, '_')}_${(s.id || '').slice(-5)}.json`
  a.click()
  URL.revokeObjectURL(url)
}

function downloadCSV(submissions) {
  const headers = ['Submitted At','Name','Company','Email','Phone','Organisation','Size','Challenges','Region','Priority Feature','Timeline','ID']
  const rows = submissions.map(s => [
    new Date(s.submittedAt).toLocaleString('en-GB'),
    s.name, s.company || '', s.email, s.phone || '',
    roleMap[s.role] || s.role || '',
    sizeMap[s.size] || s.size || '',
    Array.isArray(s.challenges) ? s.challenges.join('; ') : s.challenges || '',
    geoMap[s.region] || s.region || '',
    featMap[s.feature] || s.feature || '',
    timeMap[s.timeline] || s.timeline || '',
    s.id,
  ].map(v => `"${String(v).replace(/"/g, '""')}"`))
  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `TrustiChain_All_Leads_${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

export default function Admin() {
  const [password, setPassword] = useState('')
  const [authed, setAuthed] = useState(false)
  const [authError, setAuthError] = useState('')
  const [submissions, setSubmissions] = useState([])
  const [loading, setLoading] = useState(false)
  const [selected, setSelected] = useState(null)
  const [search, setSearch] = useState('')
  const [filterRole, setFilterRole] = useState('all')
  const [filterTimeline, setFilterTimeline] = useState('all')
  const [toast, setToast] = useState('')

  const showToast = (msg) => { setToast(msg); setTimeout(() => setToast(''), 2500) }

  const login = async () => {
    setLoading(true); setAuthError('')
    try {
      const res = await fetch('/api/submissions', { headers: { Authorization: `Bearer ${password}` } })
      if (res.status === 401) { setAuthError('Incorrect password.'); return }
      const data = await res.json()
      setSubmissions(data.submissions || [])
      setAuthed(true)
    } catch { setAuthError('Connection error. Please try again.') }
    finally { setLoading(false) }
  }

  const refresh = async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/submissions', { headers: { Authorization: `Bearer ${password}` } })
      const data = await res.json()
      setSubmissions(data.submissions || [])
      showToast('✓ Refreshed')
    } finally { setLoading(false) }
  }

  const filtered = submissions.filter(s => {
    const q = search.toLowerCase()
    const matchSearch = !q || s.name?.toLowerCase().includes(q) || s.company?.toLowerCase().includes(q) || s.email?.toLowerCase().includes(q)
    const matchRole = filterRole === 'all' || s.role === filterRole
    const matchTime = filterTimeline === 'all' || s.timeline === filterTimeline
    return matchSearch && matchRole && matchTime
  })

  const fmt = iso => new Date(iso).toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' })
  const tlColor = t => ({ asap:'#d64045', '3months':'#c9a84c', '6months':'#00b4a0', exploring:'#6b7280' }[t] || '#6b7280')
  const tlBg    = t => ({ asap:'rgba(214,64,69,0.12)', '3months':'rgba(201,168,76,0.12)', '6months':'rgba(0,180,160,0.12)', exploring:'rgba(255,255,255,0.06)' }[t] || 'rgba(255,255,255,0.06)')

  // ── LOGIN ──
  if (!authed) return (
    <>
      <Head>
        <title>TrustiChain Admin</title>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>
      <style jsx global>{`*{margin:0;padding:0;box-sizing:border-box;}body{background:#060b14;color:#f5f0e8;font-family:'DM Sans',sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;}`}</style>
      <div style={{position:'relative',width:'100%',maxWidth:'420px',padding:'3.5rem',border:'1px solid rgba(0,180,160,0.2)',background:'#0d1520',boxShadow:'0 0 80px rgba(0,180,160,0.07)'}}>
        <div style={{position:'absolute',top:0,left:0,right:0,height:'2px',background:'linear-gradient(90deg,#00b4a0,#c9a84c)'}} />
        <div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:'3rem',color:'#f5f0e8',lineHeight:1}}>TrustiChain</div>
        <div style={{fontSize:'0.62rem',letterSpacing:'0.25em',textTransform:'uppercase',color:'#00b4a0',marginBottom:'3rem',marginTop:'0.3rem'}}>Admin Dashboard</div>
        <div style={{fontSize:'0.62rem',letterSpacing:'0.15em',textTransform:'uppercase',color:'#6b7280',marginBottom:'0.5rem'}}>Password</div>
        <input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()} placeholder="Enter admin password"
          style={{width:'100%',background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.1)',color:'#f5f0e8',padding:'0.85rem 1rem',fontSize:'0.9rem',fontFamily:"'DM Sans',sans-serif",outline:'none',marginBottom:'1rem'}}
          onFocus={e=>e.target.style.borderColor='#00b4a0'} onBlur={e=>e.target.style.borderColor='rgba(255,255,255,0.1)'}
        />
        {authError && <p style={{color:'#d64045',fontSize:'0.8rem',marginBottom:'1rem'}}>{authError}</p>}
        <button onClick={login} disabled={loading}
          style={{width:'100%',background:'transparent',border:'1px solid #00b4a0',color:'#00b4a0',padding:'0.9rem',fontFamily:"'DM Sans',sans-serif",fontSize:'0.78rem',letterSpacing:'0.2em',textTransform:'uppercase',cursor:'pointer',transition:'all 0.25s'}}
          onMouseEnter={e=>{e.target.style.background='#00b4a0';e.target.style.color='#060b14'}}
          onMouseLeave={e=>{e.target.style.background='transparent';e.target.style.color='#00b4a0'}}
        >{loading ? 'Authenticating…' : 'Enter Dashboard →'}</button>
        <p style={{marginTop:'2rem',fontSize:'0.68rem',color:'#3d4d5a',textAlign:'center'}}>TrustiChain · Exhibition Lead Management</p>
      </div>
    </>
  )

  // ── DASHBOARD ──
  return (
    <>
      <Head>
        <title>Admin — TrustiChain</title>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>
      <style jsx global>{`
        *{margin:0;padding:0;box-sizing:border-box;}
        body{background:#060b14;color:#f5f0e8;font-family:'DM Sans',sans-serif;}
        ::-webkit-scrollbar{width:4px;height:4px;}::-webkit-scrollbar-thumb{background:rgba(0,180,160,0.25);}
        button,input,select{font-family:'DM Sans',sans-serif;}
        @keyframes toastIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
        @keyframes modalIn{from{opacity:0;transform:scale(0.97)}to{opacity:1;transform:none}}
      `}</style>

      {toast && <div style={{position:'fixed',bottom:'2rem',right:'2rem',background:'rgba(0,180,160,0.14)',border:'1px solid rgba(0,180,160,0.35)',color:'#00b4a0',padding:'0.7rem 1.4rem',fontSize:'0.78rem',zIndex:9999,animation:'toastIn 0.3s ease',letterSpacing:'0.1em'}}>{toast}</div>}

      <div style={{display:'flex',minHeight:'100vh'}}>
        {/* SIDEBAR */}
        <aside style={{width:'210px',background:'#080d17',borderRight:'1px solid rgba(255,255,255,0.05)',padding:'2rem 1.2rem',display:'flex',flexDirection:'column',flexShrink:0}}>
          <div style={{marginBottom:'2.5rem'}}>
            <div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:'1.6rem',color:'#f5f0e8',lineHeight:1}}>TrustiChain</div>
            <div style={{fontSize:'0.55rem',letterSpacing:'0.2em',textTransform:'uppercase',color:'#00b4a0',marginTop:'0.25rem'}}>Admin Panel</div>
          </div>
          {[['📋 Submissions',true],['📊 Analytics',false],['⚙️ Settings',false]].map(([label,active])=>(
            <div key={label} style={{padding:'0.65rem 0.9rem',marginBottom:'0.25rem',background:active?'rgba(0,180,160,0.08)':'transparent',border:active?'1px solid rgba(0,180,160,0.18)':'1px solid transparent',color:active?'#00b4a0':'#3d4d5a',fontSize:'0.82rem',cursor:'pointer'}}>{label}</div>
          ))}
          <div style={{marginTop:'auto',paddingTop:'1.5rem',borderTop:'1px solid rgba(255,255,255,0.05)'}}>
            <div style={{fontSize:'0.62rem',color:'#00b4a0',marginBottom:'0.25rem'}}>{submissions.length} total leads</div>
            <div style={{fontSize:'0.58rem',color:'#3d4d5a',marginBottom:'0.8rem'}}>Sync: {new Date().toLocaleTimeString()}</div>
            <button onClick={refresh} style={{width:'100%',background:'transparent',border:'1px solid rgba(255,255,255,0.07)',color:'#6b7280',padding:'0.5rem',fontSize:'0.65rem',letterSpacing:'0.12em',textTransform:'uppercase',cursor:'pointer',transition:'all 0.2s'}}
              onMouseEnter={e=>{e.target.style.borderColor='rgba(0,180,160,0.3)';e.target.style.color='#00b4a0'}}
              onMouseLeave={e=>{e.target.style.borderColor='rgba(255,255,255,0.07)';e.target.style.color='#6b7280'}}
            >{loading?'…':'↻ Refresh'}</button>
          </div>
        </aside>

        {/* MAIN */}
        <main style={{flex:1,overflowY:'auto',padding:'2.5rem 3rem'}}>
          {/* Header */}
          <div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',marginBottom:'2rem',flexWrap:'wrap',gap:'1rem'}}>
            <div>
              <h1 style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:'3rem',letterSpacing:'0.02em',lineHeight:1}}>Lead Submissions</h1>
              <p style={{fontSize:'0.72rem',color:'#6b7280',marginTop:'0.3rem'}}>{filtered.length} of {submissions.length} records</p>
            </div>
            <button onClick={()=>{downloadCSV(filtered);showToast(`✓ Exported ${filtered.length} leads as CSV`)}}
              style={{background:'rgba(0,180,160,0.08)',border:'1px solid rgba(0,180,160,0.25)',color:'#00b4a0',padding:'0.65rem 1.4rem',fontSize:'0.72rem',letterSpacing:'0.15em',textTransform:'uppercase',cursor:'pointer',transition:'all 0.2s'}}
              onMouseEnter={e=>e.target.style.background='rgba(0,180,160,0.18)'}
              onMouseLeave={e=>e.target.style.background='rgba(0,180,160,0.08)'}
            >↓ Export All CSV</button>
          </div>

          {/* Stats */}
          <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:'1rem',marginBottom:'2rem'}}>
            {[['Total Leads',submissions.length,'#00b4a0'],['ASAP Deploy',submissions.filter(s=>s.timeline==='asap').length,'#d64045'],['Enterprise',submissions.filter(s=>s.size==='enterprise').length,'#c9a84c'],['Manufacturers',submissions.filter(s=>s.role==='manufacturer').length,'#7c6af7']].map(([label,val,color])=>(
              <div key={label} style={{background:'#0d1520',padding:'1.2rem 1.4rem',borderTop:`2px solid ${color}`,border:'1px solid rgba(255,255,255,0.05)',borderTopColor:color}}>
                <div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:'2.5rem',color,lineHeight:1}}>{val}</div>
                <div style={{fontSize:'0.62rem',color:'#6b7280',marginTop:'0.3rem',textTransform:'uppercase',letterSpacing:'0.1em'}}>{label}</div>
              </div>
            ))}
          </div>

          {/* Filters */}
          <div style={{display:'flex',gap:'0.7rem',marginBottom:'1.5rem',flexWrap:'wrap'}}>
            <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, company, email…"
              style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',color:'#f5f0e8',padding:'0.6rem 1rem',fontSize:'0.82rem',outline:'none',width:'220px'}}
              onFocus={e=>e.target.style.borderColor='rgba(0,180,160,0.4)'} onBlur={e=>e.target.style.borderColor='rgba(255,255,255,0.07)'}
            />
            <select value={filterRole} onChange={e=>setFilterRole(e.target.value)}
              style={{background:'#0d1520',border:'1px solid rgba(255,255,255,0.07)',color:'#f5f0e8',padding:'0.6rem 1rem',fontSize:'0.82rem',outline:'none'}}>
              <option value="all">All Roles</option>
              {Object.entries(roleMap).map(([v,l])=><option key={v} value={v}>{l}</option>)}
            </select>
            <select value={filterTimeline} onChange={e=>setFilterTimeline(e.target.value)}
              style={{background:'#0d1520',border:'1px solid rgba(255,255,255,0.07)',color:'#f5f0e8',padding:'0.6rem 1rem',fontSize:'0.82rem',outline:'none'}}>
              <option value="all">All Timelines</option>
              {Object.entries(timeMap).map(([v,l])=><option key={v} value={v}>{l}</option>)}
            </select>
          </div>

          {/* Table */}
          {filtered.length === 0 ? (
            <div style={{textAlign:'center',padding:'6rem 2rem',color:'#3d4d5a',border:'1px dashed rgba(255,255,255,0.05)',fontSize:'0.85rem'}}>
              {submissions.length===0 ? '🔗 No submissions yet — share the pitch deck to start collecting leads.' : 'No records match your filters.'}
            </div>
          ) : (
            <div style={{overflowX:'auto',border:'1px solid rgba(255,255,255,0.05)'}}>
              <table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.82rem'}}>
                <thead>
                  <tr style={{borderBottom:'1px solid rgba(255,255,255,0.07)',background:'rgba(255,255,255,0.02)'}}>
                    {['Date','Name','Company','Role','Region','Timeline','Download'].map(h=>(
                      <th key={h} style={{padding:'0.8rem 1rem',textAlign:'left',fontSize:'0.58rem',letterSpacing:'0.15em',textTransform:'uppercase',color:'#3d4d5a',fontWeight:500,whiteSpace:'nowrap'}}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((s)=>(
                    <tr key={s.id} style={{borderBottom:'1px solid rgba(255,255,255,0.04)',cursor:'pointer',transition:'background 0.15s'}}
                      onMouseEnter={e=>e.currentTarget.style.background='rgba(0,180,160,0.04)'}
                      onMouseLeave={e=>e.currentTarget.style.background='transparent'}
                    >
                      <td style={{padding:'0.9rem 1rem',color:'#6b7280',whiteSpace:'nowrap',fontSize:'0.72rem'}}>{fmt(s.submittedAt)}</td>
                      <td style={{padding:'0.9rem 1rem'}} onClick={()=>setSelected(s)}>
                        <div style={{color:'#f5f0e8',fontWeight:500}}>{s.name}</div>
                        <div style={{fontSize:'0.68rem',color:'#6b7280',marginTop:'0.1rem'}}>{s.email}</div>
                      </td>
                      <td style={{padding:'0.9rem 1rem',color:'#a0aab4'}} onClick={()=>setSelected(s)}>{s.company||'—'}</td>
                      <td style={{padding:'0.9rem 1rem'}} onClick={()=>setSelected(s)}>
                        <span style={{background:'rgba(0,180,160,0.08)',border:'1px solid rgba(0,180,160,0.18)',color:'#00b4a0',padding:'0.2rem 0.55rem',fontSize:'0.65rem',whiteSpace:'nowrap'}}>
                          {roleMap[s.role]?.split(' ')[0]||s.role||'—'}
                        </span>
                      </td>
                      <td style={{padding:'0.9rem 1rem',color:'#a0aab4',fontSize:'0.78rem'}} onClick={()=>setSelected(s)}>{geoMap[s.region]||s.region||'—'}</td>
                      <td style={{padding:'0.9rem 1rem'}} onClick={()=>setSelected(s)}>
                        <span style={{background:tlBg(s.timeline),border:`1px solid ${tlColor(s.timeline)}40`,color:tlColor(s.timeline),padding:'0.2rem 0.55rem',fontSize:'0.65rem',whiteSpace:'nowrap'}}>
                          {timeMap[s.timeline]||s.timeline||'—'}
                        </span>
                      </td>
                      <td style={{padding:'0.9rem 1rem'}}>
                        <div style={{display:'flex',gap:'0.4rem'}}>
                          <button onClick={()=>{downloadTXT(s);showToast(`✓ Downloaded ${s.name.split(' ')[0]}'s profile`)}}
                            style={{background:'rgba(0,180,160,0.07)',border:'1px solid rgba(0,180,160,0.2)',color:'#00b4a0',padding:'0.3rem 0.65rem',fontSize:'0.65rem',cursor:'pointer',transition:'all 0.2s',letterSpacing:'0.05em'}}
                            onMouseEnter={e=>e.target.style.background='rgba(0,180,160,0.18)'}
                            onMouseLeave={e=>e.target.style.background='rgba(0,180,160,0.07)'}
                          >↓ TXT</button>
                          <button onClick={()=>{downloadJSON(s);showToast('✓ JSON downloaded')}}
                            style={{background:'rgba(201,168,76,0.07)',border:'1px solid rgba(201,168,76,0.2)',color:'#c9a84c',padding:'0.3rem 0.65rem',fontSize:'0.65rem',cursor:'pointer',transition:'all 0.2s',letterSpacing:'0.05em'}}
                            onMouseEnter={e=>e.target.style.background='rgba(201,168,76,0.18)'}
                            onMouseLeave={e=>e.target.style.background='rgba(201,168,76,0.07)'}
                          >↓ JSON</button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </main>
      </div>

      {/* DETAIL MODAL */}
      {selected && (
        <div style={{position:'fixed',inset:0,background:'rgba(4,8,18,0.92)',backdropFilter:'blur(10px)',zIndex:1000,display:'flex',alignItems:'center',justifyContent:'center',padding:'1rem'}}
          onClick={e=>e.target===e.currentTarget&&setSelected(null)}>
          <div style={{background:'#0d1520',border:'1px solid rgba(0,180,160,0.2)',width:'100%',maxWidth:'560px',maxHeight:'88vh',overflowY:'auto',padding:'2.8rem',position:'relative',animation:'modalIn 0.35s cubic-bezier(0.16,1,0.3,1)',boxShadow:'0 0 60px rgba(0,0,0,0.7)'}}>
            <div style={{position:'absolute',top:0,left:0,right:0,height:'2px',background:'linear-gradient(90deg,#00b4a0,#c9a84c)'}} />
            <button onClick={()=>setSelected(null)} style={{position:'absolute',top:'1rem',right:'1.2rem',background:'none',border:'none',color:'#6b7280',fontSize:'1rem',cursor:'pointer'}}>✕</button>
            <div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:'2.2rem',lineHeight:1,marginBottom:'0.2rem'}}>{selected.name}</div>
            <div style={{fontSize:'0.72rem',color:'#00b4a0',marginBottom:'0.2rem'}}>{selected.company||'No company listed'}</div>
            <div style={{fontSize:'0.62rem',color:'#3d4d5a',marginBottom:'2rem'}}>Submitted {fmt(selected.submittedAt)} · ID: {selected.id}</div>
            <div style={{display:'flex',flexDirection:'column'}}>
              {[
                ['📧 Email', selected.email, '#00b4a0'],
                ['📞 Phone', selected.phone||'—', null],
                ['🏢 Organisation', roleMap[selected.role]||selected.role||'—', null],
                ['📏 Size', sizeMap[selected.size]||selected.size||'—', null],
                ['🌍 Region', geoMap[selected.region]||selected.region||'—', null],
                ['⚡ Challenges', Array.isArray(selected.challenges)?selected.challenges.join(', '):selected.challenges||'—', null],
                ['🎯 Priority Feature', featMap[selected.feature]||selected.feature||'—', null],
                ['🗓️ Deploy Timeline', timeMap[selected.timeline]||selected.timeline||'—', tlColor(selected.timeline)],
              ].map(([label, value, color])=>(
                <div key={label} style={{display:'flex',gap:'1rem',padding:'0.85rem 0',borderBottom:'1px solid rgba(255,255,255,0.04)'}}>
                  <span style={{fontSize:'0.62rem',letterSpacing:'0.08em',textTransform:'uppercase',color:'#3d4d5a',minWidth:'160px',paddingTop:'0.15rem',flexShrink:0}}>{label}</span>
                  <span style={{fontSize:'0.85rem',color:color||'#d0d8e0',flex:1,lineHeight:1.5}}>{value}</span>
                </div>
              ))}
            </div>
            {/* Actions */}
            <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'0.6rem',marginTop:'2rem'}}>
              <a href={`mailto:${selected.email}?subject=Your TrustiChain Proposal&body=Dear ${selected.name.split(' ')[0]},%0D%0A%0D%0AThank you for your interest in TrustiChain.%0D%0A%0D%0AWe are preparing a custom proposal for ${selected.company||'your organisation'}.%0D%0A%0D%0AKind regards,%0D%0ATrustiChain Team`}
                style={{display:'flex',alignItems:'center',justifyContent:'center',padding:'0.75rem',background:'rgba(0,180,160,0.08)',border:'1px solid rgba(0,180,160,0.25)',color:'#00b4a0',textDecoration:'none',fontSize:'0.68rem',letterSpacing:'0.1em',textTransform:'uppercase',transition:'all 0.2s'}}
                onMouseEnter={e=>e.currentTarget.style.background='rgba(0,180,160,0.18)'}
                onMouseLeave={e=>e.currentTarget.style.background='rgba(0,180,160,0.08)'}
              >✉ Email</a>
              <button onClick={()=>{downloadTXT(selected);showToast('✓ TXT downloaded')}}
                style={{background:'rgba(0,180,160,0.07)',border:'1px solid rgba(0,180,160,0.2)',color:'#00b4a0',padding:'0.75rem',fontSize:'0.68rem',letterSpacing:'0.1em',textTransform:'uppercase',cursor:'pointer',transition:'all 0.2s'}}
                onMouseEnter={e=>e.target.style.background='rgba(0,180,160,0.18)'}
                onMouseLeave={e=>e.target.style.background='rgba(0,180,160,0.07)'}
              >↓ Download TXT</button>
              <button onClick={()=>{downloadJSON(selected);showToast('✓ JSON downloaded')}}
                style={{background:'rgba(201,168,76,0.07)',border:'1px solid rgba(201,168,76,0.2)',color:'#c9a84c',padding:'0.75rem',fontSize:'0.68rem',letterSpacing:'0.1em',textTransform:'uppercase',cursor:'pointer',transition:'all 0.2s'}}
                onMouseEnter={e=>e.target.style.background='rgba(201,168,76,0.18)'}
                onMouseLeave={e=>e.target.style.background='rgba(201,168,76,0.07)'}
              >↓ Download JSON</button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
